
development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: todo_development
  pool: 5
  username: ubuntu
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: db/production.pg
  pool: 5
